### ISSUE TITLE
Remove eval-in-project?

### ISSUE THREAD

**Issue by technomancy** [rm-hull/lein-nvd#10]
> The core module is run outside of leiningen (there is a conflict in the version of Lucene that is used in the dependency-check libs vs. the version of Lucene that is embedded in Leiningen).

I saw this in the readme and thought I should let you know that Leiningen 2.8.0-RC1 and onwards will not ship with its own Lucene, so the `eval-in-project` might not be necessary any more. I might be able to cook up a patch to remove it, but of course it would not be compatible with 2.7.1 and older.

**Comment by rm-hull** [comment]
Good to know, but I would say (at this stage) that it's paramount to maintain compatibility across versions.

**Comment by rm-hull** [comment]
In https://github.com/rm-hull/lein-nvd/issues/38#issuecomment-504537895, @nickmbailey wrote:

> In my head I've been pondering if this really needs to use leins 'eval-in-project' which is what causes the guava conflict between dependency-check and my project. Seems like it could evaluate outside of the project but still pass the project classpath to dependency check. That's probably worth a separate issue though.

This is more a question for @technomancy really, but is it sufficient to set `false` at this line: https://github.com/rm-hull/lein-nvd/blob/master/plugin/project.clj#L26 ?

If not, could you advise how we can go about removing `eval-in-project` - I think sufficient time has passed such that supporting 2.7.1 and older should now be a non-issue.

**Comment by nickmbailey** [comment]
I think you need to actually remove the macro call here:

https://github.com/rm-hull/lein-nvd/blob/master/plugin/src/leiningen/nvd.clj#L87

**Comment by technomancy** [comment]
@rm-hull Good question. That file is about the Leiningen configuration for the plugin during development; if you take that out then the tests will run outside Leiningen's process and will not have access to `leiningen.core.main` etc which it needs.

So @nickmbailey is right that the solution is to drop the `eval-in` call and simply call the functions it calls directly. This will require making the `nvd-clojure` library a direct dependency on the `lein-nvd` plugin. This should greatly simplify things and remove the need to write JSON to the filesystem to send opts from the plugin to the library code; things can simply be passed as function arguments.

**Comment by stig** [comment]
I think this issue can be closed now? It appears fixed by #44, but for some reason was not auto-fixed by merging that.
