### ISSUE TITLE
Boot support?

### ISSUE THREAD

**Issue by kennyjwilli** [rm-hull/lein-nvd#12]
Would you be open to adding Boot support to this project?

**Comment by rm-hull** [comment]
Absolutely, although I have no background or experience in boot; but am happy to take on PRs and/or add collaborators onto the project. 

If we do go down the route of adding boot support however, it might be better to consider either:
* renaming the project so it isn't specific to leiningen, or 
* create a completely separate **boot-nvd** project that depends on the core https://clojars.org/nvd-clojure/.

I haven't got any particular preferences here, but if there is an appetite for this, I would be interested in canvassing people's opinions.

**Comment by kennyjwilli** [comment]
I've got a PR almost ready. Is there a way to set the output directory of all the nvd tasks?

**Comment by kennyjwilli** [comment]
In terms of project structure, I suggest looking at [environ](https://github.com/weavejester/environ).

**Comment by rm-hull** [comment]
> Is there a way to set the output directory of all the nvd tasks?

There is a `nvd.output-dir` property which can be specified which is used by the reports to set the output directory, see https://github.com/rm-hull/lein-nvd/blob/master/src/nvd/report.clj#L40

**Comment by vemv** [comment]
`nvd-clojure` (part of this repo) is a discrete Clojure program that can be invoked regardless of tooling choices.

That might suffice to consider this issue fixed.

Cheers - V
