### ISSUE TITLE
Where does `lein-nvd` cache its DB?

### ISSUE THREAD

**Issue by xiongtx** [rm-hull/lein-nvd#17]
CI services usually allow data to be cached. In this case, we can cache the NVE DB based on the hash of `project.clj`. But it's not obvious where the the data NVD downloads is kept.

**Comment by rm-hull** [comment]
By default, _dependencyCheck_ (the underlying library we use) will populate the database inside your maven repository:

```
 $ ls -l ~/.m2/repository/org/owasp/dependency-check-utils/3.1.0/data/
total 612464
-rw-r--r--  1 rhu  staff  313581568 17 Jan 02:08 dc.h2.db
```

You can override the location if necessary, by supplying a `:data-directory` parameter as alluded to in the [configuration options](https://github.com/rm-hull/lein-nvd#configuration-options) section of the README.

**Comment by xiongtx** [comment]
Cool--so caching `~/.m2` should be sufficient.
