### ISSUE TITLE
Option to not report "OK" rows?

### ISSUE THREAD

**Issue by vemv** [rm-hull/lein-nvd#30]
Hi there,

thanks for this project!

Would it sound good to add an option to not render rows like the following?

```
| tools.nrepl-0.2.12.jar                                                    | OK                                 |
```

In large projects, `OK` rows greatly outnumber vulnerable ones, so they become a nuisance (I have to scroll a lot to find the 'meat').

**Comment by rm-hull** [comment]
Makes sense, I'll add that as a feature

**Comment by vemv** [comment]
Tried out, works like a charm.

Thanks for this one!
