### ISSUE TITLE
Clojure CLI tools deps.edn support?

### ISSUE THREAD

**Issue by wilsonverrency** [rm-hull/lein-nvd#31]
Support for tools deps? (see #12)

**Comment by rm-hull** [comment]
Can you be more specific in what you mean?

**Comment by wilsonverrency** [comment]
Would be cool if we could run the checks from a project using the deps.edn format from Clojure CLI tools.

**Comment by seanpoulter** [comment]
I'm also interested in this. Has anyone found a tool to scan deps.edn or ClojureScript dependencies?

**Comment by manuviswam** [comment]
I'm also looking for the same. Did anyone find a tool to scan deps.edn dependencies?

**Comment by dotemacs** [comment]
You can use this library/plugin with Clojure CLI right now.

In your `deps.edn`, add:

```clojure
 :aliases   {:nvd {:extra-deps {lein-nvd/lein-nvd {:mvn/version "1.4.1"}
                                org.slf4j/slf4j-nop {:mvn/version "1.7.30"}}
                   :main-opts ["-m" "nvd.task.check"]}}
```

On the command line run it:

```
$ clj -M:nvd
```

The only issue that I've noticed is that `nvd.task.check/make-classpath` is not playing nicely with > Java 8, due to the way classpath is generated. But that's a separate issue, but one that you should be aware when trying the above.

**Comment by dotemacs** [comment]
> The only issue that I've noticed is that nvd.task.check/make-classpath is not playing nicely with > Java 8, due to the way classpath is generated. But that's a separate issue, but one that you should be aware when trying the above.

Took care of that in #56

**Comment by dotemacs** [comment]
Considering that #57 & #58 were merged and that the README shows how to use this library with Clojure CLI tools deps.edn, maybe this issue is no longer relevant and can be closed?

**Comment by rm-hull** [comment]
@dotemacs agreed.
