### ISSUE TITLE
Not possible to disable analyzers

### ISSUE THREAD

**Issue by nickmbailey** [rm-hull/lein-nvd#39]
Currently, lein-nvd creates the dependency check engine by first creating a settings object with the no arg constructor, and then passing that settings object to the single arg constructor for Engine.

https://github.com/rm-hull/lein-nvd/blob/master/src/nvd/config.clj#L98

Then, after that, lein-nvd goes back and mutates the settings object to configure certain analyzers/settings on or off.

Unfortunately, it's actually in the constructor for Engine that dependency-check initializes all of its analyzers.

https://github.com/jeremylong/DependencyCheck/blob/master/core/src/main/java/org/owasp/dependencycheck/Engine.java#L250

So it's too late too disable analyzers at the point that lein-nvd tries to modify the settings. Usually in the case of things like the assembly analyzer, it just fails to find dotnet on osx and disables itself during initialization so there isn't an issue. In my case the new sonatype oss analyzer has a guava conflict with some of my project dependencies and fails during initialization.

**Comment by rm-hull** [comment]
Yes, I think you are correct - good spot.

**Comment by rm-hull** [comment]
1.2.0 released which should contain a fix for this issue
