### ISSUE TITLE
Possible feature: ignore a dependency

### ISSUE THREAD

**Issue by tervorz** [rm-hull/lein-nvd#48]
Thanks for all your work on this, @rm-hull!

I have a question: would you be opposed to a pull request with an `:nvd` option to basically ignore a dependency listed in the `project.clj`? It would come with some very clear warnings about what's being ignored. I was thinking a regex pattern that would remove items from the classpath list that's getting scanned.

I understand this isn't ideal, but for me I think it's a difference between getting an automated NVD scan working on our code-bases and just giving up.

Background:

At my company, we have a home-rolled library that would theoretically get scanned every time it's built. However, when a _consuming_ project lists that library in its dependency list, I'm getting some weird proxy error. 

The library is internal-only, hosted on an internal artifactory, and for whatever reason I can't get any combination of proxy settings or artifactory analyzers to work. I've considered reaching out to some co-workers who are more aware of our networking settings, but I'm not sure how far I'll get.

**Comment by rm-hull** [comment]
Happy to accept a PR. 
If possible please try and add tests around the behaviour you are adding.

**Comment by tjbrandt** [comment]
Ok, if I go the PR route, I'll definitely add tests. Thanks!

**Comment by vemv** [comment]
A possible alternative approach would be to place these dependencies in a separate Lein profile, e.g. `:my-company`, and then when running NVD one would simply not add the `+my-company` directive to the `lein` invocation.

Of course there's the drawback of having to add `+my-company` to all other commands (`repl`, `test` etc) but personally I do advanced Lein profile management in all cases, anyway

**Comment by tjbrandt** [comment]
That's a good idea. I'm just starting to use it, but if lein-nvd supports profiles, I could potentially make an nvd profile that excludes that dependency?

Rumor has it someone else got lein-nvd working in their project within the company, so there may be hope. But if that doesn't pan out, I'll explore the lein profiles option before bothering with a PR. Thanks @vemv !

**Comment by vemv** [comment]
> I could potentially make an nvd profile that excludes that dependency?

That's a nice twist - hadn't thought of that! Indeed Lein has a top-level `:exclusions` key: https://github.com/technomancy/leiningen/blob/bc368fa68d17c39b930eeb3bd150c626b934083c/sample.project.clj#L91

...I guess that you could have a `:nvd {:exclusions [...]}` profile. Would be cleaner than the approach I initially described.

**Comment by vemv** [comment]
Perhaps we can close this issue since profile and :exclusions management works pretty well.

**Comment by hoxu** [comment]
Thanks for the README link, I must have missed that, expecting to find it under "Configuration options"!
