### ISSUE TITLE
CHANGELOG.md

### ISSUE THREAD

**Issue by dotemacs** [rm-hull/lein-nvd#60]
Hello @rm-hull 

What do you think of adding the CHANGELOG.md for the project?

I'd be happy to add it prior to the merge of #58 & #59.

And maybe even adding a pull request template, where the users are asked/prompted to update the changelog when submitting their PR?

Thanks

**Comment by rm-hull** [comment]
Yes probably. Although there would (hopefully) not be too much change on this project as it is just a thin wrapper around dependency-check, and that doesn't appear to have changed in a while

**Comment by dotemacs** [comment]
Fair enough, I'll close it. Thanks
