### ISSUE TITLE
lein nvd 1.2.0 not working 

### ISSUE THREAD

**Issue by cksharma11** [rm-hull/lein-nvd#89]
Hi,

I'm getting error while running `lein nvd check` 

```
Syntax error (ExceptionInfo) compiling at (/tmp/form-init14862117128822202941.clj:1:74).
org.owasp.dependencycheck.exception.ExceptionCollection
```

The error only happens when it runs in ci env interestingly it works fine when I run it in my local

Any idea?

**Comment by vemv** [comment]
Hi!

please run the task with the following Lein option so that you get a stacktrace:

`:jvm-opts ["-Dclojure.main.report=stderr"]`

then post it here

Cheers - V

**Comment by cksharma11** [comment]
Hi @vemv 

Thanks for the quick reply the problem happens only in the pipeline agent, 

will need to get logs from the same, but I'll share the logs

**Comment by cksharma11** [comment]
I did upgraded the version to use the latest one and now getting error with strace

```
using nvd-clojure:  and dependency-check: 5.3.2
Encountered errors while analyzing: One or more exceptions occurred during analysis:
	'void com.google.common.base.Preconditions.checkState(boolean, java.lang.String, java.lang.Object)'
	'void com.google.common.base.Preconditions.checkState(boolean, java.lang.String, java.lang.Object)'
	'void com.google.common.base.Preconditions.checkState(boolean, java.lang.String, java.lang.Object)'
	'void com.google.common.base.Preconditions.checkState(boolean, java.lang.String, java.lang.Object)'
....
....
...
```

**Comment by vemv** [comment]
Please post a complete stacktrace - there should be plenty of filenames involved, an exception name etc

Cheers - V

**Comment by cksharma11** [comment]
> Please post a complete stacktrace - there should be plenty of filenames involved, an exception name etc
> 
> Cheers - V

I've the same issue mentioned over -  https://www.gitmemory.com/issue/rm-hull/lein-nvd/73/805055117 

Stacktrace is also similar

**Comment by vemv** [comment]
Please post it over here for posterity

**Comment by cksharma11** [comment]
> > Please post a complete stacktrace - there should be plenty of filenames involved, an exception name etc
> > Cheers - V
> 
> I've the same issue mentioned over - https://www.gitmemory.com/issue/rm-hull/lein-nvd/73/805055117
> 
> Stacktrace is also similar

Trace - 

```
#error {
 :cause 'void com.google.common.base.Preconditions.checkState(boolean, java.lang.String, java.lang.Object)'
 :via
 [{:type java.lang.NoSuchMethodError
   :message 'void com.google.common.base.Preconditions.checkState(boolean, java.lang.String, java.lang.Object)'
   :at [org.sonatype.ossindex.service.client.cache.DirectoryCache <init> DirectoryCache.java 84]}]
 :trace
 [[org.sonatype.ossindex.service.client.cache.DirectoryCache <init> DirectoryCache.java 84]
  [org.sonatype.ossindex.service.client.cache.DirectoryCache$Configuration create DirectoryCache.java 328]
  [org.sonatype.ossindex.service.client.internal.OssindexClientImpl <init> OssindexClientImpl.java 96]
  [org.owasp.dependencycheck.data.ossindex.OssindexClientFactory create OssindexClientFactory.java 119]
  [org.owasp.dependencycheck.analyzer.OssIndexAnalyzer requestReports OssIndexAnalyzer.java 196]
  [org.owasp.dependencycheck.analyzer.OssIndexAnalyzer analyzeDependency OssIndexAnalyzer.java 138]
  [org.owasp.dependencycheck.analyzer.AbstractAnalyzer analyze AbstractAnalyzer.java 131]
  [org.owasp.dependencycheck.AnalysisTask call AnalysisTask.java 88]
  [org.owasp.dependencycheck.AnalysisTask call AnalysisTask.java 37]
  [java.util.concurrent.FutureTask run FutureTask.java 264]
  [java.util.concurrent.ThreadPoolExecutor runWorker ThreadPoolExecutor.java 1128]
  [java.util.concurrent.ThreadPoolExecutor$Worker run ThreadPoolExecutor.java 628]
  [java.lang.Thread run Thread.java 829]]}
#error {
```

**Comment by vemv** [comment]
FWIW that stacktrace is not complete, as `#error {` in the last line hints. Please be considerate of collaborator time - if you're asked for a stacktrace, provide the full stacktrace! :)

(You can always change names if there are private files)

Anyway, it's enough info for the time being. `java.lang.NoSuchMethodError` tells us that it's a problem related to dependency management / classpath computation.

That's a quite frequent problem when using lein-nvd. Accordingly we created this guide and related API:

https://github.com/rm-hull/lein-nvd#avoiding-classpath-interference

The first suggested command over there (`Lein example`) might just work.

If the problem persists, you might have to follow the next piece of advice `For extra isolation, it is recommended that you invoke nvd.task.check from outside your project`

Hope it helps!

**Comment by cksharma11** [comment]
Hi @vemv apologies for that and thank you so much for quick support

**Comment by cksharma11** [comment]
@vemv Sorry if it's a dump question but I'm getting below error while running

lein run -m nvd.task.check "" "$(lein with-profile -user,-dev classpath)"

```
Warning: implicit hook found: lein-environ.plugin/hooks
Hooks are deprecated and will be removed in a future version.
Warning: implicit hook found: lein-environ.plugin/hooks
Hooks are deprecated and will be removed in a future version.
Can't find 'nvd.task.check' as .class or .clj for lein run: please check the spelling.
Syntax error (FileNotFoundException) compiling at (/private/var/folders/9q/383w1knj3j10fxr0rvy65d_80000gn/T/form-init17918837598688706921.clj:1:126).
Could not locate nvd/task/check__init.class, nvd/task/check.clj or nvd/task/check.cljc on classpath.

Full report at:
/var/folders/9q/383w1knj3j10fxr0rvy65d_80000gn/T/clojure-1708364996348719684.edn

```

**Comment by cksharma11** [comment]
> Hi @vemv apologies for that and thank you so much for quick support

Yes that fixed the issue, thank you :)

**Comment by vemv** [comment]
Cheers 🍻
