### ISSUE TITLE
Unable to resolve symbol: simple-symbol? in this context

### ISSUE THREAD

**Issue by fabio-anzola** [rm-hull/lein-nvd#90]
Hello, can someone help me?
When running `lein nvd check` many different dependencies get retrieved. During this process I get an exception (see below).
Am I missing something? / Am I doing something wrong?

===

Retrieving nvd-clojure/nvd-clojure/1.5.0/nvd-clojure-1.5.0.jar from clojars
Retrieving lein-kibit/lein-kibit/0.0.8/lein-kibit-0.0.8.jar from clojars
Retrieving jonase/kibit/0.0.8/kibit-0.0.8.jar from clojars
clojure.lang.Compiler$CompilerException: java.lang.RuntimeException: Unable to resolve symbol: simple-symbol? in this context, compiling:(clojure/tools/deps/alpha.clj:54:8)
 at clojure.lang.Compiler.analyze (Compiler.java:6688)
    clojure.lang.Compiler.analyze (Compiler.java:6625)
    clojure.lang.Compiler$InvokeExpr.parse (Compiler.java:3766)
    clojure.lang.Compiler.analyzeSeq (Compiler.java:6870)
    clojure.lang.Compiler.analyze (Compiler.java:6669)
    clojure.lang.Compiler.analyze (Compiler.java:6625)
    clojure.lang.Compiler$IfExpr$Parser.parse (Compiler.java:2792)
    clojure.lang.Compiler.analyzeSeq (Compiler.java:6868)
    clojure.lang.Compiler.analyze (Compiler.java:6669)
    clojure.lang.Compiler.analyze (Compiler.java:6625)
    clojure.lang.Compiler$BodyExpr$Parser.parse (Compiler.java:6005)
    clojure.lang.Compiler$FnMethod.parse (Compiler.java:5380)
    clojure.lang.Compiler$FnExpr.parse (Compiler.java:3972)
    clojure.lang.Compiler.analyzeSeq (Compiler.java:6866)
    clojure.lang.Compiler.analyze (Compiler.java:6669)
    clojure.lang.Compiler.analyzeSeq (Compiler.java:6856)
    clojure.lang.Compiler.analyze (Compiler.java:6669)
    clojure.lang.Compiler.access$300 (Compiler.java:38)
    clojure.lang.Compiler$DefExpr$Parser.parse (Compiler.java:590)
    clojure.lang.Compiler.analyzeSeq (Compiler.java:6868)
    clojure.lang.Compiler.analyze (Compiler.java:6669)
    clojure.lang.Compiler.analyze (Compiler.java:6625)
    clojure.lang.Compiler.eval (Compiler.java:6931)
...

**Comment by vemv** [comment]
Sounds like you're using an old version of Lein. Newer Lein versions use more recent Clojure compiler versions, which will offer `simple-symbol? `

**Comment by fabio-anzola** [comment]
Hi! Thank you for the fast reply!!
I installed lein via apt, so I'm not sure if I got the latest one. I have this version: Leiningen 2.8.1 on Java 1.8.0_292 OpenJDK 64-Bit Server VM 
Which one would you recommend?

**Comment by vemv** [comment]
Yes 2.8 is quite old by now

I'd suggest simply installing lein latest following https://github.com/technomancy/leiningen/blob/master/README.md , it's a simple self-contained script.

**Comment by fabio-anzola** [comment]
This took my longer than expected, but now I have the latest version installed. 
I can now run `lein nvd check` without an exception. Thank you!

**Comment by vemv** [comment]
Cheers 🍻 feel free to close the issue

**Comment by fabio-anzola** [comment]
Awesome, thanks!
